### ISSUE TITLE
General

### ISSUE THREAD

**Issue by anuexists** [anurajkashyap/Probability-Statistics-Assignments#6]

**Comment by anuexists** [comment]
Lets discuss about the ownership of the problems. @akshaythorave  & @TheLiteRunner  please suggest about this. I am thinking of two of us doing 2 problems each and the 3rd one responsible for a problem and report making.

**Comment by akshaythorave** [comment]
Hii guys
I am thinking to work on first and third problem

**Comment by anuexists** [comment]
Ok, so @akshaythorave will do #1 and #3. @TheLiteRunner will do #2 and #4. and I, @anurajkashyap will do #5 and will responsible for the report.
Any help required, please put it in the issues sections of the respective problems.
